server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/mybatisplus?useSSL=false&serverTimeZone=UTC
#增加日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #设置实体类前缀来和数据库中的表名一样
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto
      #类型别名所对应的包
  type-aliases-package: com.bjpowernode.vo.User
  # 配置扫描通用枚举
  type-enums-package: com.bjpowernode.enums
